# artifacts_root: artifacts

# data_ingestion:
#   root_dir: artifacts/data_ingestion
#   source_URL: https://github.com/Rashi-Kathuria/Text-Summarizer-Project-2/raw/main/dataset.zip
#   local_data_file: artifacts/data_ingestion/data.zip
#   unzip_dir: artifacts/data_ingestion